[package]
name = "tskv"
version.workspace = true
edition.workspace = true


[[bin]]
name = "tskv-writer"
path = "src/main.rs"

[dependencies]
config = { path = "../config" }
cache = { path = "../common/cache"}
error_code = { path = "../common/error_code" }
memory_pool = { path = "../common/memory_pool" }
meta = { path = "../meta" }
metrics = { path = "../common/metrics" }
models = { path = "../common/models" }
protos = { path = "../common/protos", features = ["test"] }
replication = { path = "../replication" }
trace = { path = "../common/trace" }
utils = { path = "../common/utils" }
http_protocol = { path = "../common/http_protocol" }

rdkafka = {versin= 0.36}
clap = { workspace = true, features = ["derive", "env"] }
reqwest = { workspace = true, features = ["rustls-tls", "json"], default-features = false }
arrow = { workspace = true, features = ["test_utils"] }
arrow-array = { workspace = true }
async-backtrace = { workspace = true, optional = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
bzip2 = { workspace = true }
chrono = { workspace = true }
crc32fast = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
datafusion = { workspace = true }
dircpy = { workspace = true }
datafusion-proto = { workspace = true }
flatbuffers = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true, features = ["std", "thread-pool"] }
integer-encoding = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
minivec = { workspace = true }
mio = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true }
num_enum = { workspace = true }
once_cell = { workspace = true }
openraft = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true, features = ["nightly", "send_guard"] }
pco = {workspace = true}
radixdb = { workspace = true, features = ["custom-store"] }
rand = { workspace = true }
regex = { workspace = true }
roaring = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
skiplist = { workspace = true }
sled = { workspace = true }
snafu = { workspace = true }
snap = { workspace = true }
static_assertions = { workspace = true }
sysinfo = { workspace = true, optional = false }
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-util = { workspace = true }
walkdir = { workspace = true }
zstd = { workspace = true }
tonic = { workspace = true }
stable-vec = { workspace = true }
arrow-schema = { workspace = true }
md-5 = { workspace = true }
hex = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
rio = { version = "0.9.4", optional = true }
tokio-uring = { version = "0.4", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }


[features]
default = []
io_uring = ["rio"]
backtrace = ["async-backtrace"]

[dev-dependencies]
serial_test = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
parking_lot = { workspace = true, features = ["nightly"] }
rand = { workspace = true }
tempfile = { workspace = true }
arrow = { workspace = true, features = ["test_utils"] }

[[bench]]
harness = false
name = "kvcore_bench"

[[bench]]
harness = false
name = "data_merge"