[package]
name = "utils"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trace = { path = "../trace" }

async-backtrace = { workspace = true, optional = true }
libc = { workspace = true }
tokio = { workspace = true, features = ["full", "tracing"] }
futures = { workspace = true }
[target.'cfg(unix)'.dependencies]
pprof = { workspace = true, features = ["flamegraph", "protobuf-codec", "frame-pointer"] }
tikv-jemalloc-ctl = { workspace = true }

[features]
default = []
backtrace = ["async-backtrace"]

[dev-dependencies]
rand = { workspace = true }
